version: "3"
services:
  grabber:
    build: ./
    image: grabber
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - grabberData:/grabber/data
volumes:
  grabberData: {}